export const typeIcons: Record<string, string> = {
    bug: "/icons/bug.svg",
    dark: "/icons/dark.svg",
    dragon: "/icons/dragon.svg",
    electric: "/icons/electric.svg",
    fairy: "/icons/fairy.svg",
    fighting: "/icons/fighting.svg",
    fire: "/icons/fire.svg",
    flying: "/icons/flying.svg",
    ghost: "/icons/ghost.svg",
    grass: "/icons/grass.svg",
    ground: "/icons/ground.svg",
    ice: "/icons/ice.svg",
    normal: "/icons/normal.svg",
    poison: "/icons/poison.svg",
    psychic: "/icons/psychic.svg",
    rock: "/icons/rock.svg",
    steel: "/icons/steel.svg",
    water: "/icons/water.svg",
};

export const typeColors: Record<string, string> = {
    bug: "#A8B820",
    dark: "#705848",
    dragon: "#7038F8",
    electric: "#F8D030",
    fairy: "#EE99AC",
    fighting: "#C03028",
    fire: "#F08030",
    flying: "#A890F0",
    ghost: "#705898",
    grass: "#78C850",
    ground: "#E0C068",
    ice: "#98D8D8",
    normal: "#A8A878",
    poison: "#A040A0",
    psychic: "#F85888",
    rock: "#B8A038",
    steel: "#B8B8D0",
    water: "#6890F0",
};
