import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/NavBar";
import localFont from "next/font/local";
const pokemonFont = localFont({
    src: "../fonts/pokemon.ttf",
    variable: "--font-pokemon",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${pokemonFont.variable}`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
